### ISSUE TITLE
Automatic tagging of Fedora-based images with Fedora version of the base image during push

### ISSUE THREAD

**Issue by pkubatrh** [sclorg/build-and-push-action#14]
Currently we have to define the version of the underlying base image in the configuration of the action. The base image provides an envvar (eg ."FGC=f35") that could be used for this instead so that we do not have to remember to update it everytime.

**Comment by zmiklank** [comment]
This seems too Fedora-specific to integrate into `build-and-push action`. Instead, I proposed a solution (which is, I admit, not the prettiest one) for an `s2i-base-image`, which is the only place where this functionality is needed. See linked PR.
Let me please know, if this solution is sufficient for you.
