### ISSUE TITLE
Publish the action also into GitHub Market place.

### ISSUE THREAD

**Issue by phracek** [sclorg/build-and-push-action#15]
I don't see this action on GitHub Marketplace like `testing-farm-as-github-action` https://github.com/marketplace/actions/schedule-tests-on-testing-farm.

Can you please publish it?

**Comment by zmiklank** [comment]
Hi, I did not publish the action, because it is only used within SCLorg. But I can release it if you think, it is needed.

**Comment by zmiklank** [comment]
It is available now: https://github.com/marketplace/actions/build-and-push-images-to-registry
