### ISSUE TITLE
Do not generate files with distgen

### ISSUE THREAD

**Issue by zmiklank** [sclorg/build-and-push-action#19]
The files should be already correctly generated in the git repository.

This should be implemented only after we have some check, that the files are regenerated properly and are up to date.
I will then start working on this.

CC: @pkubatrh @frenzymadness @phracek

**Comment by praiskup** [comment]
> The files should be already correctly generated in the git repository.

More info about how this is done would be nice ^^^

**Comment by zmiklank** [comment]
> > The files should be already correctly generated in the git repository.
> 
> More info about how this is done would be nice ^^^

Sure.

Sclorg container images with distgen generated content already have the generated files for all versions available in the git repository. This is part of the code contribution to the repositories: in every PR also files need to be manually regenerated and commited. 

Therefore the check running in a PR would be introduced, for verifying, that the generated files are up to date. That way the build-and-push action would always run on up to date sources that were tested in the PR.
