### ISSUE TITLE
'Version' input has hidden meaning in the action's body

### ISSUE THREAD

**Issue by zmiklank** [sclorg/build-and-push-action#3]
The 'version' input stands also for the relative path to the Dockerfile used for building the image. This could lead to some problems in the future and should be investigated.

**Comment by phracek** [comment]
This is a correct issue. The version does not make sense. https://github.com/sclorg/build-and-push-action/blob/main/action.yml#L65 It could be path_to_dockerfile. Also, step short version can be either named else or used here directly https://github.com/sclorg/build-and-push-action/blob/main/action.yml#L110

**Comment by zmiklank** [comment]
Solved with https://github.com/sclorg/build-and-push-action/pull/5, closing.
